# .github/workflows/code-review.yml
name: Pull Request Code Review & Security Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (if exists)
        run: npm run lint || echo "No lint script defined"

      - name: Run security audit
        run: npm audit --audit-level=moderate || echo "Security warnings found"

  # CodeQL Security Analysis
  codeql-analysis:
    name: "CodeQL Security Scan"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
