# .github/workflows/deploy.yml
name: Deployment Pipeline (Mock Deploy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mock-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build || echo "No build script found"

      - name: Simulate Deployment
        run: |
          echo "🚀 Starting deployment process..."
          echo "Uploading files to production server (simulated)"
          echo "✅ Deployment Successful!"
